spring.application.name=spring_session_cookie

server.port=8085

spring.datasource.url=jdbc:mysql://localhost:3306/test?useSSL=false&&allowPublicKeyRetrieval=true&&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=184703
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.servlet.session.timeout=1m
